name: Docker build & Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Get tagged version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish to Github Repo
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: trauth
          addLatest: true
          tags: ${{ steps.get_version.outputs.VERSION }}, latest
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }} 
      - name: Publish to Docker Repo
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leonjza/trauth
          addLatest: true
          tags: ${{ steps.get_version.outputs.VERSION }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
